package drools.rules;

import br.edu.ifsc.adubacao.model.Laudo;

global br.edu.ifsc.adubacao.model.Diagnostico diagnostico;

dialect  "mvel"

rule "Diagnostico_indice_SMP44_ph65"
    when
        Laudo(getIndiceSMP() <= 4.4, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(29.0);
end

rule "Diagnostico_indice_SMP45_ph65"
    when
        Laudo(getIndiceSMP() == 4.5, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(24.0);
end

rule "Diagnostico_indice_SMP46_ph65"
    when
        Laudo(getIndiceSMP() == 4.6, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(20.0);
end

rule "Diagnostico_indice_SMP47_ph65"
    when
        Laudo(getIndiceSMP() == 4.7, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(17.5);
end

rule "Diagnostico_indice_SMP48_ph65"
    when
        Laudo(getIndiceSMP() == 4.8, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(15.7);
end

rule "Diagnostico_indice_SMP49_ph65"
    when
        Laudo(getIndiceSMP() == 4.9, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(14.2);
end

rule "Diagnostico_indice_SMP50_ph65"
    when
        Laudo(getIndiceSMP() == 5.0, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(13.3);
end

rule "Diagnostico_indice_SMP51_ph65"
    when
        Laudo(getIndiceSMP() == 5.1, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(12.3);
end

rule "Diagnostico_indice_SMP52_ph65"
    when
        Laudo(getIndiceSMP() == 5.2, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(11.3);
end

rule "Diagnostico_indice_SMP53_ph65"
    when
        Laudo(getIndiceSMP() == 5.3, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(10.4);
end

rule "Diagnostico_indice_SMP54_ph65"
    when
        Laudo(getIndiceSMP() == 5.4, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(9.5);
end

rule "Diagnostico_indice_SMP55_ph65"
    when
        Laudo(getIndiceSMP() == 5.5, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(8.6);
end

rule "Diagnostico_indice_SMP56_ph65"
    when
        Laudo(getIndiceSMP() == 5.6, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(7.8);
end

rule "Diagnostico_indice_SMP57_ph65"
    when
        Laudo(getIndiceSMP() == 5.7, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(7.0);
end

rule "Diagnostico_indice_SMP58_ph65"
    when
        Laudo(getIndiceSMP() == 5.8, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(6.3);
end

rule "Diagnostico_indice_SMP59_ph65"
    when
        Laudo(getIndiceSMP() == 5.9, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(5.6);
end

rule "Diagnostico_indice_SMP60_ph65"
    when
        Laudo(getIndiceSMP() == 6.0, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(4.9);
end

rule "Diagnostico_indice_SMP61_ph65"
    when
        Laudo(getIndiceSMP() == 6.1, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(4.3);
end

rule "Diagnostico_indice_SMP62_ph65"
    when
        Laudo(getIndiceSMP() == 6.2, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(3.7);
end

rule "Diagnostico_indice_SMP63_ph65"
    when
        Laudo(getIndiceSMP() == 6.3, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(3.1);
end

rule "Diagnostico_indice_SMP64_ph65"
    when
        Laudo(getIndiceSMP() == 6.4, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(3.1);
end

rule "Diagnostico_indice_SMP65_ph65"
    when
        Laudo(getIndiceSMP() == 6.5, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(2.1);
end

rule "Diagnostico_indice_SMP66_ph65"
    when
        Laudo(getIndiceSMP() == 6.6, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(1.6);
end

rule "Diagnostico_indice_SMP67_ph65"
    when
        Laudo(getIndiceSMP() == 6.7, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(1.2);
end

rule "Diagnostico_indice_SMP68_ph65"
    when
        Laudo(getIndiceSMP() == 6.8, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(0.8);
end

rule "Diagnostico_indice_SMP69_ph65"
    when
        Laudo(getIndiceSMP() == 6.9, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(0.5);
end

rule "Diagnostico_indice_SMP70_ph65"
    when
        Laudo(getIndiceSMP() == 7.0, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(0.2);
end

rule "Diagnostico_indice_SMP71_ph65"
    when
        Laudo(getIndiceSMP() == 7.1, getpHReferencia() == 6.5)
    then
        diagnostico.calcularQuantidadeCalcario(0);
end

rule "Diagnostico_indice_SMP44_ph60"
    when
        Laudo(getIndiceSMP() <= 4.4, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(21.0);
end

rule "Diagnostico_indice_SMP45_ph60"
    when
        Laudo(getIndiceSMP() == 4.5, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(17.3);
end

rule "Diagnostico_indice_SMP46_ph60"
    when
        Laudo(getIndiceSMP() == 4.6, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(15.1);
end

rule "Diagnostico_indice_SMP47_ph60"
    when
        Laudo(getIndiceSMP() == 4.7, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(13.3);
end

rule "Diagnostico_indice_SMP48_ph60"
    when
        Laudo(getIndiceSMP() == 4.8, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(11.9);
end

rule "Diagnostico_indice_SMP49_ph60"
    when
        Laudo(getIndiceSMP() == 4.9, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(10.7);
end

rule "Diagnostico_indice_SMP50_ph60"
    when
        Laudo(getIndiceSMP() == 5.0, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(9.9);
end

rule "Diagnostico_indice_SMP51_ph60"
    when
        Laudo(getIndiceSMP() == 5.1, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(9.1);
end

rule "Diagnostico_indice_SMP52_ph60"
    when
        Laudo(getIndiceSMP() == 5.2, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(8.3);
end

rule "Diagnostico_indice_SMP53_ph60"
    when
        Laudo(getIndiceSMP() == 5.3, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(7.5);
end

rule "Diagnostico_indice_SMP54_ph60"
    when
        Laudo(getIndiceSMP() == 5.4, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(6.8);
end

rule "Diagnostico_indice_SMP55_ph60"
    when
        Laudo(getIndiceSMP() == 5.5, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(6.1);
end

rule "Diagnostico_indice_SMP56_ph60"
    when
        Laudo(getIndiceSMP() == 5.6, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(5.4);
end

rule "Diagnostico_indice_SMP57_ph60"
    when
        Laudo(getIndiceSMP() == 5.7, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(4.8);
end

rule "Diagnostico_indice_SMP58_ph60"
    when
        Laudo(getIndiceSMP() == 5.8, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(4.2);
end

rule "Diagnostico_indice_SMP59_ph60"
    when
        Laudo(getIndiceSMP() == 5.9, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(3.7);
end

rule "Diagnostico_indice_SMP60_ph60"
    when
        Laudo(getIndiceSMP() == 6.0, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(3.2);
end

rule "Diagnostico_indice_SMP61_ph60"
    when
        Laudo(getIndiceSMP() == 6.1, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(2.7);
end

rule "Diagnostico_indice_SMP62_ph60"
    when
        Laudo(getIndiceSMP() == 6.2, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(2.2);
end

rule "Diagnostico_indice_SMP63_ph60"
    when
        Laudo(getIndiceSMP() == 6.3, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(1.8);
end

rule "Diagnostico_indice_SMP64_ph60"
    when
        Laudo(getIndiceSMP() == 6.4, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(1.4);
end

rule "Diagnostico_indice_SMP65_ph60"
    when
        Laudo(getIndiceSMP() == 6.5, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(1.1);
end

rule "Diagnostico_indice_SMP66_ph60"
    when
        Laudo(getIndiceSMP() == 6.6, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(0.8);
end

rule "Diagnostico_indice_SMP67_ph60"
    when
        Laudo(getIndiceSMP() == 6.7, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(0.5);
end

rule "Diagnostico_indice_SMP68_ph60"
    when
        Laudo(getIndiceSMP() == 6.8, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(0.3);
end

rule "Diagnostico_indice_SMP69_ph60"
    when
        Laudo(getIndiceSMP() == 6.9, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(0.2);
end

rule "Diagnostico_indice_SMP70_ph60"
    when
        Laudo(getIndiceSMP() == 7.0, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(0);
end

rule "Diagnostico_indice_SMP71_ph60"
    when
        Laudo(getIndiceSMP() == 7.1, getpHReferencia() == 6.0)
    then
        diagnostico.calcularQuantidadeCalcario(0);
end