package drools.rules;

import br.edu.ifsc.adubacao.model.Diagnostico;

global br.edu.ifsc.adubacao.model.Diagnostico diagnostico;

dialect  "mvel"

rule "Diagnostico_teores_P_class_1_MB"
    when
        Diagnostico(classeArgila == 1, laudo.fosforoP <= 3)
    then
        diagnostico.setClasseFosforoP("Muito Baixo");
end

rule "Diagnostico_teores_P_class_2_MB"
    when
        Diagnostico(classeArgila == 2, laudo.fosforoP <= 4)
    then
        diagnostico.setClasseFosforoP("Muito Baixo");
end

rule "Diagnostico_teores_P_class_3_MB"
    when
        Diagnostico(classeArgila == 3, laudo.fosforoP <= 6)
    then
        diagnostico.setClasseFosforoP("Muito Baixo");
end

rule "Diagnostico_teores_P_class_4_MB"
    when
        Diagnostico(classeArgila == 4, laudo.fosforoP <= 10)
    then
        diagnostico.setClasseFosforoP("Muito Baixo");
end

rule "Diagnostico_teores_P_class_1_B"
    when
        Diagnostico(classeArgila == 1, laudo.fosforoP >= 3.1 && laudo.fosforoP <= 6)
    then
        diagnostico.setClasseFosforoP("Baixo");
end

rule "Diagnostico_teores_P_class_2_B"
    when
        Diagnostico(classeArgila == 2, laudo.fosforoP >= 4.1 && laudo.fosforoP <= 8)
    then
        diagnostico.setClasseFosforoP("Baixo");
end

rule "Diagnostico_teores_P_class_3_B"
    when
        Diagnostico(classeArgila == 3, laudo.fosforoP >= 6.1 && laudo.fosforoP <= 12)
    then
        diagnostico.setClasseFosforoP("Baixo");
end

rule "Diagnostico_teores_P_class_4_B"
    when
        Diagnostico(classeArgila == 4, laudo.fosforoP >= 10.1 && laudo.fosforoP <= 20)
    then
        diagnostico.setClasseFosforoP("Baixo");
end

rule "Diagnostico_teores_P_class_1_M"
    when
        Diagnostico(classeArgila == 1, laudo.fosforoP >= 6.1 && laudo.fosforoP <= 9)
    then
        diagnostico.setClasseFosforoP("Médio");
end

rule "Diagnostico_teores_P_class_2_M"
    when
        Diagnostico(classeArgila == 2, laudo.fosforoP >= 8.1 && laudo.fosforoP <= 12)
    then
        diagnostico.setClasseFosforoP("Médio");
end

rule "Diagnostico_teores_P_class_3_M"
    when
        Diagnostico(classeArgila == 3, laudo.fosforoP >= 12.1 && laudo.fosforoP <= 18)
    then
        diagnostico.setClasseFosforoP("Médio");
end

rule "Diagnostico_teores_P_class_4_M"
    when
        Diagnostico(classeArgila == 4, laudo.fosforoP >= 20.1 && laudo.fosforoP <= 30)
    then
        diagnostico.setClasseFosforoP("Médio");
end

rule "Diagnostico_teores_P_class_1_A"
    when
        Diagnostico(classeArgila == 1, laudo.fosforoP >= 9.1 && laudo.fosforoP <= 18)
    then
        diagnostico.setClasseFosforoP("Alto");
end

rule "Diagnostico_teores_P_class_2_A"
    when
        Diagnostico(classeArgila == 2, laudo.fosforoP >= 12.1 && laudo.fosforoP <= 24)
    then
        diagnostico.setClasseFosforoP("Alto");
end

rule "Diagnostico_teores_P_class_3_A"
    when
        Diagnostico(classeArgila == 3, laudo.fosforoP >= 18.1 && laudo.fosforoP <= 36)
    then
        diagnostico.setClasseFosforoP("Alto");
end

rule "Diagnostico_teores_P_class_4_A"
    when
        Diagnostico(classeArgila == 4, laudo.fosforoP >= 30.1 && laudo.fosforoP <= 60)
    then
        diagnostico.setClasseFosforoP("Alto");
end

rule "Diagnostico_teores_P_class_1_MA"
    when
        Diagnostico(classeArgila == 1, laudo.fosforoP > 18)
    then
        diagnostico.setClasseFosforoP("Muito Alto");
end

rule "Diagnostico_teores_P_class_2_MA"
    when
        Diagnostico(classeArgila == 2, laudo.fosforoP > 24)
    then
        diagnostico.setClasseFosforoP("Muito Alto");
end

rule "Diagnostico_teores_P_class_3_MA"
    when
        Diagnostico(classeArgila == 3, laudo.fosforoP > 36)
    then
        diagnostico.setClasseFosforoP("Muito Alto");
end

rule "Diagnostico_teores_P_class_4_MA"
    when
        Diagnostico(classeArgila == 4, laudo.fosforoP > 60)
    then
        diagnostico.setClasseFosforoP("Muito Alto");
end

rule "Diagnostico_teores_Ca_B"
   when
       Diagnostico(laudo.calcioTrocavelCaTroc < 2)
   then
       diagnostico.setClasseCalcioCa("Baixo");
end

rule "Diagnostico_teores_Ca_M"
   when
       Diagnostico(laudo.calcioTrocavelCaTroc >= 2 && laudo.calcioTrocavelCaTroc <= 4)
   then
       diagnostico.setClasseCalcioCa("Médio");
end

rule "Diagnostico_teores_Ca_A"
   when
       Diagnostico(laudo.calcioTrocavelCaTroc > 4)
   then
       diagnostico.setClasseCalcioCa("Alto");
end

rule "Diagnostico_teores_Mg_B"
   when
       Diagnostico(laudo.magnesioTrocavelMgTroc < 0.5)
   then
       diagnostico.setClasseMagnesioMg("Baixo");
end

rule "Diagnostico_teores_Mg_M"
   when
       Diagnostico(laudo.magnesioTrocavelMgTroc >= 0.5 && laudo.magnesioTrocavelMgTroc <= 1)
   then
       diagnostico.setClasseMagnesioMg("Médio");
end

rule "Diagnostico_teores_Mg_A"
   when
       Diagnostico(laudo.magnesioTrocavelMgTroc > 1)
   then
       diagnostico.setClasseMagnesioMg("Alto");
end
